.TH "headers Directory Reference" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConfig\&.h\fP"
.br
.RI "\fIstructure of a player \fP"
.ti -1c
.RI "file \fBConsts\&.h\fP"
.br
.RI "\fIall enums and constants \fP"
.ti -1c
.RI "file \fBEngine\&.h\fP"
.br
.ti -1c
.RI "file \fBIA\&.h\fP"
.br
.ti -1c
.RI "file \fBmmanager\&.h\fP"
.br
.ti -1c
.RI "file \fBMove\&.h\fP"
.br
.in -1c
