.TH "sources/Consts.c" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/Consts.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/Consts\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBMAX_PAWN\fP =8"
.br
.ti -1c
.RI "const uint8_t \fBMAX_KING\fP =1"
.br
.ti -1c
.RI "const uint8_t \fBMAX_QUEEN\fP =1"
.br
.ti -1c
.RI "const uint8_t \fBMAX_ROOK\fP =2"
.br
.ti -1c
.RI "const uint8_t \fBMAX_KNIGHT\fP =2"
.br
.ti -1c
.RI "const uint8_t \fBMAX_BISHOP\fP =2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t MAX_BISHOP =2"

.SS "const uint8_t MAX_KING =1"

.SS "const uint8_t MAX_KNIGHT =2"

.SS "const uint8_t MAX_PAWN =8"

.SS "const uint8_t MAX_QUEEN =1"

.SS "const uint8_t MAX_ROOK =2"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
