.TH "Game" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCOLOR\fP \fBcolor_distrib\fP [\fBBOARD_SIZE\fP][\fBBOARD_SIZE\fP]"
.br
.ti -1c
.RI "\fBPiece\fP * \fBpieces\fP"
.br
.ti -1c
.RI "size_t \fBstack\fP [\fBMAX_PIECES\fP]"
.br
.ti -1c
.RI "size_t \fBpieces_size\fP"
.br
.ti -1c
.RI "\fBCOLOR\fP \fBturn\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBCOLOR\fP color_distrib[\fBBOARD_SIZE\fP][\fBBOARD_SIZE\fP]"

.SS "\fBPiece\fP* pieces"

.SS "size_t pieces_size"

.SS "size_t stack[\fBMAX_PIECES\fP]"

.SS "\fBCOLOR\fP turn"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
