.TH "sources/main.c" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./headers/Config\&.h'\fP
.br
\fC#include '\&.\&./headers/Move\&.h'\fP
.br
\fC#include '\&.\&./headers/Engine\&.h'\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argv, char **argc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBD\fP = 2"
.br
.ti -1c
.RI "const uint8_t \fBW\fP = 200"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargv, char **argc)"

.SH "Variable Documentation"
.PP 
.SS "const uint8_t D = 2"

.SS "const uint8_t W = 200"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
