.TH "Moves" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Moves \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Move\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPosition\fP * \fBposition\fP"
.br
.ti -1c
.RI "size_t \fBnumber\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t number"

.SS "\fBPosition\fP* position"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
