.TH "Node" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Engine\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "\fBN_DATA\fP \fBdata_type\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBprev_level\fP"
.br
.ti -1c
.RI "struct \fBList\fP * \fBnext_level\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBN_DATA\fP data_type"

.SS "\fBNode\fP* next"

.SS "struct \fBList\fP* next_level"

.SS "\fBNode\fP* prev"

.SS "struct \fBNode\fP* prev_level"

.SS "int score"

.SS "void* value"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
