.TH "Piece" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Piece \- 
.PP
\fBPiece\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBCOLOR\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBPosition\fP \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPiece\fP struct\&. 


.SH "Field Documentation"
.PP 
.SS "\fBCOLOR\fP color"

.SS "\fBPosition\fP position"

.SS "\fBType\fP type"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
