.TH "Piece_Array" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Piece_Array \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBPiece\fP ** \fBpieces\fP"
.br
.ti -1c
.RI "size_t \fBnumber\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t number"

.SS "\fBPiece\fP** pieces"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
