.TH "Player" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCOLOR\fP \fBplayer_type\fP"
.br
.ti -1c
.RI "\fBPiece\fP ** \fBpieces\fP"
.br
.ti -1c
.RI "size_t * \fBstack\fP [\fBMAX_PIECES\fP]"
.br
.ti -1c
.RI "size_t \fBnumber\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t number"

.SS "\fBPiece\fP** pieces"

.SS "\fBCOLOR\fP player_type"

.SS "size_t* stack[\fBMAX_PIECES\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
