.TH "Position" 3 "Wed Oct 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- 
.PP
structure of positions x and y are clamped between 0 and 7,to represent to position of a piece on the board\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t \fBx\fP"
.br
.ti -1c
.RI "int8_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure of positions x and y are clamped between 0 and 7,to represent to position of a piece on the board\&. 


.SH "Field Documentation"
.PP 
.SS "int8_t x"

.SS "int8_t y"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
